services:
  api:
    image: jglchen/chirper-api
    command: "php artisan serve --host=0.0.0.0"
    ports:
      - 8000:8000
    volumes:
      - chirper-api-sqlite:/app/database

  next:
    image: jglchen/chirper-next
    ports:
      - 3000:3000

volumes:
  chirper-api-sqlite: